// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin/themes" | "/contact" | "/devadmin/dwarakadmin/login" | "/devadmin/dwarakadmin/mylogin" | "/devadmin/dwarakadmin/mylogin/analytics" | "/devadmin/dwarakadmin/mylogin/contact" | "/devadmin/dwarakadmin/mylogin/content/get-started" | "/devadmin/dwarakadmin/mylogin/forms" | "/devadmin/dwarakadmin/mylogin/history" | "/devadmin/dwarakadmin/mylogin/inquiries/[id]" | "/devadmin/dwarakadmin/mylogin/portfolio" | "/devadmin/dwarakadmin/mylogin/pricing" | "/devadmin/dwarakadmin/mylogin/pricing/edit/[id]" | "/devadmin/dwarakadmin/mylogin/pricing/new" | "/devadmin/dwarakadmin/mylogin/projects" | "/devadmin/dwarakadmin/mylogin/projects/edit/[id]" | "/devadmin/dwarakadmin/mylogin/projects/new" | "/devadmin/dwarakadmin/mylogin/services" | "/devadmin/dwarakadmin/mylogin/submissions" | "/devadmin/dwarakadmin/mylogin/themes" | "/faq" | "/get-started" | "/portfolio" | "/portfolio/[slug]" | "/pricing" | "/project/[id]" | "/services"
type AppRouteHandlerRoutes = "/api/admin/analytics" | "/api/admin/auth/login" | "/api/admin/auth/logout" | "/api/admin/dashboard" | "/api/admin/forms" | "/api/admin/forms/[id]" | "/api/admin/history" | "/api/admin/pricing" | "/api/admin/pricing/[id]" | "/api/admin/projects" | "/api/admin/projects/[id]" | "/api/admin/sections" | "/api/admin/sections/[id]" | "/api/admin/services" | "/api/admin/services/[id]" | "/api/auth/[...nextauth]" | "/api/contact-info" | "/api/forms/fields" | "/api/forms/fields/[id]" | "/api/inquiry" | "/api/inquiry/[id]" | "/api/pricing" | "/api/pricing/[id]" | "/api/projects" | "/api/projects/[id]" | "/api/projects/slug/[slug]" | "/api/public/pricing" | "/api/public/sections/[page]" | "/api/sections" | "/api/seed-projects" | "/api/submissions" | "/api/submissions/[id]" | "/api/themes" | "/api/themes/[id]" | "/api/themes/active" | "/api/track"
type PageRoutes = never
type LayoutRoutes = "/" | "/devadmin/dwarakadmin/mylogin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin/themes": {}
  "/api/admin/analytics": {}
  "/api/admin/auth/login": {}
  "/api/admin/auth/logout": {}
  "/api/admin/dashboard": {}
  "/api/admin/forms": {}
  "/api/admin/forms/[id]": { "id": string; }
  "/api/admin/history": {}
  "/api/admin/pricing": {}
  "/api/admin/pricing/[id]": { "id": string; }
  "/api/admin/projects": {}
  "/api/admin/projects/[id]": { "id": string; }
  "/api/admin/sections": {}
  "/api/admin/sections/[id]": { "id": string; }
  "/api/admin/services": {}
  "/api/admin/services/[id]": { "id": string; }
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/contact-info": {}
  "/api/forms/fields": {}
  "/api/forms/fields/[id]": { "id": string; }
  "/api/inquiry": {}
  "/api/inquiry/[id]": { "id": string; }
  "/api/pricing": {}
  "/api/pricing/[id]": { "id": string; }
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/slug/[slug]": { "slug": string; }
  "/api/public/pricing": {}
  "/api/public/sections/[page]": { "page": string; }
  "/api/sections": {}
  "/api/seed-projects": {}
  "/api/submissions": {}
  "/api/submissions/[id]": { "id": string; }
  "/api/themes": {}
  "/api/themes/[id]": { "id": string; }
  "/api/themes/active": {}
  "/api/track": {}
  "/contact": {}
  "/devadmin/dwarakadmin/login": {}
  "/devadmin/dwarakadmin/mylogin": {}
  "/devadmin/dwarakadmin/mylogin/analytics": {}
  "/devadmin/dwarakadmin/mylogin/contact": {}
  "/devadmin/dwarakadmin/mylogin/content/get-started": {}
  "/devadmin/dwarakadmin/mylogin/forms": {}
  "/devadmin/dwarakadmin/mylogin/history": {}
  "/devadmin/dwarakadmin/mylogin/inquiries/[id]": { "id": string; }
  "/devadmin/dwarakadmin/mylogin/portfolio": {}
  "/devadmin/dwarakadmin/mylogin/pricing": {}
  "/devadmin/dwarakadmin/mylogin/pricing/edit/[id]": { "id": string; }
  "/devadmin/dwarakadmin/mylogin/pricing/new": {}
  "/devadmin/dwarakadmin/mylogin/projects": {}
  "/devadmin/dwarakadmin/mylogin/projects/edit/[id]": { "id": string; }
  "/devadmin/dwarakadmin/mylogin/projects/new": {}
  "/devadmin/dwarakadmin/mylogin/services": {}
  "/devadmin/dwarakadmin/mylogin/submissions": {}
  "/devadmin/dwarakadmin/mylogin/themes": {}
  "/faq": {}
  "/get-started": {}
  "/portfolio": {}
  "/portfolio/[slug]": { "slug": string; }
  "/pricing": {}
  "/project/[id]": { "id": string; }
  "/services": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/devadmin/dwarakadmin/mylogin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
