// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/admin/themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/themes">> = Specific
  const handler = {} as typeof import("../../../src/app/admin/themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/login">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/contact">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/content/get-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/content/get-started">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/content/get-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/forms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/forms">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/forms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/history">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/inquiries/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/inquiries/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/inquiries/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/pricing/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/pricing/edit/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/pricing/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/pricing/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/pricing/new">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/pricing/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/projects/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/projects/edit/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/projects/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/projects/new">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/services">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/submissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/submissions">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/submissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/themes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/devadmin/dwarakadmin/mylogin/themes">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/themes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/get-started/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/get-started">> = Specific
  const handler = {} as typeof import("../../../src/app/get-started/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../../src/app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/project/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/project/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/project/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/forms/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forms/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/forms/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/forms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forms">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/forms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/history">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/pricing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pricing/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/pricing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/sections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sections/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/sections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/sections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sections">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/sections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/services/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/services/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/services">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/contact-info/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact-info">> = Specific
  const handler = {} as typeof import("../../../src/app/api/contact-info/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/forms/fields/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forms/fields/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/forms/fields/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/forms/fields/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forms/fields">> = Specific
  const handler = {} as typeof import("../../../src/app/api/forms/fields/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inquiry/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiry/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inquiry/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/inquiry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inquiry">> = Specific
  const handler = {} as typeof import("../../../src/app/api/inquiry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pricing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pricing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/projects/slug/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/slug/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/projects/slug/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/public/sections/[page]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/sections/[page]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/public/sections/[page]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/sections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sections">> = Specific
  const handler = {} as typeof import("../../../src/app/api/sections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/seed-projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seed-projects">> = Specific
  const handler = {} as typeof import("../../../src/app/api/seed-projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/submissions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submissions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/submissions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/submissions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/themes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/themes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/themes/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes/active">> = Specific
  const handler = {} as typeof import("../../../src/app/api/themes/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/themes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/themes">> = Specific
  const handler = {} as typeof import("../../../src/app/api/themes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/track/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/track">> = Specific
  const handler = {} as typeof import("../../../src/app/api/track/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/devadmin/dwarakadmin/mylogin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/devadmin/dwarakadmin/mylogin">> = Specific
  const handler = {} as typeof import("../../../src/app/devadmin/dwarakadmin/mylogin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
